name: Deploy
on:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run check
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - if: ${{ env.ACT }}
        run: flyctl deploy --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} --build-only --remote-only .
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - if: ${{ !env.ACT }}
        run: flyctl deploy --remote-only .
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
